# Generated by Django 5.2.6 on 2025-09-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_acc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("customer", "Mijoz")],
                default="customer",
                max_length=20,
            ),
        ),
    ]
